"""
Seed script - adds 57 more books to reach 100 total
Run: python seed_books3.py
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))

from app.database import SessionLocal, init_db
from app.models import Book, User

init_db()

BOOKS = [
    {"title": "The Alchemist's Secret", "author": "Scott Mariani", "category": "Thriller", "isbn": "9780007276554", "condition": "Good", "price": 110.0, "description": "A fast-paced thriller featuring ex-SAS soldier Ben Hope on a dangerous mission.", "image_url": "https://covers.openlibrary.org/b/isbn/9780007276554-L.jpg", "swap_available": True},
    {"title": "Becoming", "author": "Michelle Obama", "category": "Biography", "isbn": "9781524763138", "condition": "Like New", "price": 220.0, "description": "An intimate memoir by the former First Lady of the United States.", "image_url": "https://covers.openlibrary.org/b/isbn/9781524763138-L.jpg", "swap_available": False},
    {"title": "The Pragmatic Programmer", "author": "Andrew Hunt", "category": "Technology", "isbn": "9780135957059", "condition": "Good", "price": 280.0, "description": "Your journey to mastery — a classic guide for software developers.", "image_url": "https://covers.openlibrary.org/b/isbn/9780135957059-L.jpg", "swap_available": False},
    {"title": "Clean Code", "author": "Robert C. Martin", "category": "Technology", "isbn": "9780132350884", "condition": "Like New", "price": 299.0, "description": "A handbook of agile software craftsmanship for writing clean, readable code.", "image_url": "https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg", "swap_available": False},
    {"title": "The Midnight Sun", "author": "Stephenie Meyer", "category": "Romance", "isbn": "9780316707046", "condition": "Like New", "price": 145.0, "description": "Twilight retold from Edward Cullen's perspective.", "image_url": "https://covers.openlibrary.org/b/isbn/9780316707046-L.jpg", "swap_available": True},
    {"title": "Cosmos", "author": "Carl Sagan", "category": "Science", "isbn": "9780345539434", "condition": "Good", "price": 160.0, "description": "A personal voyage through the universe by the legendary astronomer Carl Sagan.", "image_url": "https://covers.openlibrary.org/b/isbn/9780345539434-L.jpg", "swap_available": True},
    {"title": "The Art of War", "author": "Sun Tzu", "category": "Philosophy", "isbn": "9781599869773", "condition": "Good", "price": 80.0, "description": "An ancient Chinese military treatise on strategy and tactics.", "image_url": "https://covers.openlibrary.org/b/isbn/9781599869773-L.jpg", "swap_available": True},
    {"title": "Gone Girl", "author": "Gillian Flynn", "category": "Thriller", "isbn": "9780307588371", "condition": "Good", "price": 130.0, "description": "A psychological thriller about a marriage gone terrifyingly wrong.", "image_url": "https://covers.openlibrary.org/b/isbn/9780307588371-L.jpg", "swap_available": True},
    {"title": "The Giver", "author": "Lois Lowry", "category": "Fiction", "isbn": "9780544336261", "condition": "Acceptable", "price": 90.0, "description": "A dystopian novel about a boy who discovers the dark secrets of his seemingly perfect society.", "image_url": "https://covers.openlibrary.org/b/isbn/9780544336261-L.jpg", "swap_available": True},
    {"title": "Narcopolis", "author": "Jeet Thayil", "category": "Fiction", "isbn": "9780143419648", "condition": "Good", "price": 115.0, "description": "A Booker-shortlisted novel set in the opium dens of Bombay.", "image_url": "https://covers.openlibrary.org/b/isbn/9780143419648-L.jpg", "swap_available": False},
    {"title": "The White Tiger", "author": "Aravind Adiga", "category": "Fiction", "isbn": "9781416562603", "condition": "Good", "price": 120.0, "description": "A Booker Prize-winning novel about class struggle and entrepreneurship in India.", "image_url": "https://covers.openlibrary.org/b/isbn/9781416562603-L.jpg", "swap_available": True},
    {"title": "Five Point Someone", "author": "Chetan Bhagat", "category": "Fiction", "isbn": "9788129104595", "condition": "Acceptable", "price": 75.0, "description": "A story of three friends struggling through IIT — the inspiration for 3 Idiots.", "image_url": "https://covers.openlibrary.org/b/isbn/9788129104595-L.jpg", "swap_available": True},
    {"title": "2 States", "author": "Chetan Bhagat", "category": "Romance", "isbn": "9788129115300", "condition": "Good", "price": 80.0, "description": "The story of a Punjabi boy and a Tamil girl trying to get their parents to agree to their marriage.", "image_url": "https://covers.openlibrary.org/b/isbn/9788129115300-L.jpg", "swap_available": True},
    {"title": "The God of Small Things", "author": "Arundhati Roy", "category": "Fiction", "isbn": "9780812979657", "condition": "Good", "price": 130.0, "description": "A Booker Prize-winning novel about forbidden love in Kerala, India.", "image_url": "https://covers.openlibrary.org/b/isbn/9780812979657-L.jpg", "swap_available": False},
    {"title": "Malgudi Days", "author": "R.K. Narayan", "category": "Fiction", "isbn": "9780143031031", "condition": "Acceptable", "price": 85.0, "description": "A collection of short stories set in the fictional South Indian town of Malgudi.", "image_url": "https://covers.openlibrary.org/b/isbn/9780143031031-L.jpg", "swap_available": True},
    {"title": "The Namesake", "author": "Jhumpa Lahiri", "category": "Fiction", "isbn": "9780618485222", "condition": "Good", "price": 110.0, "description": "A story of an Indian immigrant family navigating identity and belonging in America.", "image_url": "https://covers.openlibrary.org/b/isbn/9780618485222-L.jpg", "swap_available": False},
    {"title": "Interpreter of Maladies", "author": "Jhumpa Lahiri", "category": "Fiction", "isbn": "9780395927205", "condition": "Like New", "price": 105.0, "description": "Pulitzer Prize-winning short stories about Indian and Indian-American lives.", "image_url": "https://covers.openlibrary.org/b/isbn/9780395927205-L.jpg", "swap_available": True},
    {"title": "The Jungle Book", "author": "Rudyard Kipling", "category": "Classic", "isbn": "9780141321684", "condition": "Good", "price": 70.0, "description": "The classic tale of Mowgli, a boy raised by wolves in the Indian jungle.", "image_url": "https://covers.openlibrary.org/b/isbn/9780141321684-L.jpg", "swap_available": True},
    {"title": "Siddhartha", "author": "Hermann Hesse", "category": "Philosophy", "isbn": "9780553208849", "condition": "Good", "price": 95.0, "description": "A spiritual journey of self-discovery set in ancient India.", "image_url": "https://covers.openlibrary.org/b/isbn/9780553208849-L.jpg", "swap_available": True},
    {"title": "The Old Man and the Sea", "author": "Ernest Hemingway", "category": "Classic", "isbn": "9780684801223", "condition": "Acceptable", "price": 80.0, "description": "A Pulitzer Prize-winning novella about an aging Cuban fisherman's struggle with a giant marlin.", "image_url": "https://covers.openlibrary.org/b/isbn/9780684801223-L.jpg", "swap_available": False},
    {"title": "Of Mice and Men", "author": "John Steinbeck", "category": "Classic", "isbn": "9780140177398", "condition": "Good", "price": 75.0, "description": "A tragic story of two displaced migrant ranch workers during the Great Depression.", "image_url": "https://covers.openlibrary.org/b/isbn/9780140177398-L.jpg", "swap_available": True},
    {"title": "The Grapes of Wrath", "author": "John Steinbeck", "category": "Classic", "isbn": "9780143039433", "condition": "Acceptable", "price": 100.0, "description": "A Pulitzer Prize-winning novel about an Oklahoma family's migration during the Great Depression.", "image_url": "https://covers.openlibrary.org/b/isbn/9780143039433-L.jpg", "swap_available": False},
    {"title": "Crime and Punishment", "author": "Fyodor Dostoevsky", "category": "Classic", "isbn": "9780140449136", "condition": "Good", "price": 110.0, "description": "A psychological novel about a student who commits murder and struggles with guilt.", "image_url": "https://covers.openlibrary.org/b/isbn/9780140449136-L.jpg", "swap_available": True},
    {"title": "War and Peace", "author": "Leo Tolstoy", "category": "Classic", "isbn": "9780199232765", "condition": "Acceptable", "price": 150.0, "description": "An epic novel about Russian society during the Napoleonic Wars.", "image_url": "https://covers.openlibrary.org/b/isbn/9780199232765-L.jpg", "swap_available": False},
    {"title": "The Brothers Karamazov", "author": "Fyodor Dostoevsky", "category": "Classic", "isbn": "9780374528379", "condition": "Good", "price": 130.0, "description": "A philosophical novel about faith, doubt, and morality through a family drama.", "image_url": "https://covers.openlibrary.org/b/isbn/9780374528379-L.jpg", "swap_available": True},
    {"title": "Don Quixote", "author": "Miguel de Cervantes", "category": "Classic", "isbn": "9780060934347", "condition": "Acceptable", "price": 120.0, "description": "The first modern novel — a story of a man who believes himself to be a knight.", "image_url": "https://covers.openlibrary.org/b/isbn/9780060934347-L.jpg", "swap_available": False},
    {"title": "Frankenstein", "author": "Mary Shelley", "category": "Classic", "isbn": "9780141439471", "condition": "Good", "price": 85.0, "description": "The original science fiction horror novel about a scientist who creates a living creature.", "image_url": "https://covers.openlibrary.org/b/isbn/9780141439471-L.jpg", "swap_available": True},
    {"title": "Dracula", "author": "Bram Stoker", "category": "Classic", "isbn": "9780141439846", "condition": "Good", "price": 90.0, "description": "The classic Gothic horror novel that introduced Count Dracula to the world.", "image_url": "https://covers.openlibrary.org/b/isbn/9780141439846-L.jpg", "swap_available": True},
    {"title": "The Picture of Dorian Gray", "author": "Oscar Wilde", "category": "Classic", "isbn": "9780141439570", "condition": "Like New", "price": 88.0, "description": "A Gothic novel about a man whose portrait ages while he remains young.", "image_url": "https://covers.openlibrary.org/b/isbn/9780141439570-L.jpg", "swap_available": False},
    {"title": "Wuthering Heights", "author": "Emily Brontë", "category": "Classic", "isbn": "9780141439556", "condition": "Good", "price": 80.0, "description": "A dark romantic novel about the passionate and destructive love between Heathcliff and Catherine.", "image_url": "https://covers.openlibrary.org/b/isbn/9780141439556-L.jpg", "swap_available": True},
    {"title": "Jane Eyre", "author": "Charlotte Brontë", "category": "Classic", "isbn": "9780141441146", "condition": "Good", "price": 82.0, "description": "A coming-of-age story about an orphaned girl who becomes a governess and falls in love.", "image_url": "https://covers.openlibrary.org/b/isbn/9780141441146-L.jpg", "swap_available": True},
    {"title": "The Count of Monte Cristo", "author": "Alexandre Dumas", "category": "Classic", "isbn": "9780140449266", "condition": "Acceptable", "price": 140.0, "description": "An adventure novel about a man who escapes prison and seeks revenge on those who betrayed him.", "image_url": "https://covers.openlibrary.org/b/isbn/9780140449266-L.jpg", "swap_available": True},
    {"title": "Les Misérables", "author": "Victor Hugo", "category": "Classic", "isbn": "9780451419439", "condition": "Good", "price": 135.0, "description": "An epic novel about justice, love, and redemption in 19th century France.", "image_url": "https://covers.openlibrary.org/b/isbn/9780451419439-L.jpg", "swap_available": False},
    {"title": "The Little Prince", "author": "Antoine de Saint-Exupéry", "category": "Fiction", "isbn": "9780156012195", "condition": "Like New", "price": 95.0, "description": "A poetic tale about a young prince who travels the universe and learns about life and love.", "image_url": "https://covers.openlibrary.org/b/isbn/9780156012195-L.jpg", "swap_available": True},
    {"title": "The Stranger", "author": "Albert Camus", "category": "Philosophy", "isbn": "9780679720201", "condition": "Good", "price": 90.0, "description": "An existentialist novel about a man who commits a murder and faces his own indifference.", "image_url": "https://covers.openlibrary.org/b/isbn/9780679720201-L.jpg", "swap_available": True},
    {"title": "Lolita", "author": "Vladimir Nabokov", "category": "Classic", "isbn": "9780679723165", "condition": "Acceptable", "price": 105.0, "description": "A controversial and literary novel narrated by a man obsessed with a 12-year-old girl.", "image_url": "https://covers.openlibrary.org/b/isbn/9780679723165-L.jpg", "swap_available": False},
    {"title": "One Hundred Years of Solitude", "author": "Gabriel García Márquez", "category": "Fiction", "isbn": "9780060883287", "condition": "Good", "price": 145.0, "description": "A landmark of magical realism following seven generations of the Buendía family.", "image_url": "https://covers.openlibrary.org/b/isbn/9780060883287-L.jpg", "swap_available": True},
    {"title": "Love in the Time of Cholera", "author": "Gabriel García Márquez", "category": "Romance", "isbn": "9780307389732", "condition": "Good", "price": 130.0, "description": "A story of unrequited love that spans over fifty years.", "image_url": "https://covers.openlibrary.org/b/isbn/9780307389732-L.jpg", "swap_available": True},
    {"title": "The Handmaid's Tale", "author": "Margaret Atwood", "category": "Fiction", "isbn": "9780385490818", "condition": "Like New", "price": 150.0, "description": "A dystopian novel set in a totalitarian theocracy where women are enslaved.", "image_url": "https://covers.openlibrary.org/b/isbn/9780385490818-L.jpg", "swap_available": False},
    {"title": "Flowers for Algernon", "author": "Daniel Keyes", "category": "Science Fiction", "isbn": "9780156030304", "condition": "Good", "price": 100.0, "description": "A story of a man with an intellectual disability who undergoes an experiment to increase his intelligence.", "image_url": "https://covers.openlibrary.org/b/isbn/9780156030304-L.jpg", "swap_available": True},
    {"title": "Ender's Game", "author": "Orson Scott Card", "category": "Science Fiction", "isbn": "9780812550702", "condition": "Good", "price": 120.0, "description": "A gifted child is trained at a military school in space to fight an alien invasion.", "image_url": "https://covers.openlibrary.org/b/isbn/9780812550702-L.jpg", "swap_available": True},
    {"title": "Foundation", "author": "Isaac Asimov", "category": "Science Fiction", "isbn": "9780553293357", "condition": "Good", "price": 125.0, "description": "A mathematician develops a plan to preserve civilization during the fall of a galactic empire.", "image_url": "https://covers.openlibrary.org/b/isbn/9780553293357-L.jpg", "swap_available": False},
    {"title": "Neuromancer", "author": "William Gibson", "category": "Science Fiction", "isbn": "9780441569595", "condition": "Acceptable", "price": 110.0, "description": "The cyberpunk novel that defined a genre — a hacker hired for one last job.", "image_url": "https://covers.openlibrary.org/b/isbn/9780441569595-L.jpg", "swap_available": True},
    {"title": "The Name of the Wind", "author": "Patrick Rothfuss", "category": "Fantasy", "isbn": "9780756404741", "condition": "Like New", "price": 165.0, "description": "The first day of the story of Kvothe — a legendary wizard and musician.", "image_url": "https://covers.openlibrary.org/b/isbn/9780756404741-L.jpg", "swap_available": True},
    {"title": "A Game of Thrones", "author": "George R.R. Martin", "category": "Fantasy", "isbn": "9780553573404", "condition": "Good", "price": 180.0, "description": "The first book of A Song of Ice and Fire — epic fantasy of power and betrayal.", "image_url": "https://covers.openlibrary.org/b/isbn/9780553573404-L.jpg", "swap_available": True},
    {"title": "The Fellowship of the Ring", "author": "J.R.R. Tolkien", "category": "Fantasy", "isbn": "9780618346257", "condition": "Good", "price": 170.0, "description": "The first part of The Lord of the Rings — Frodo's journey to destroy the One Ring.", "image_url": "https://covers.openlibrary.org/b/isbn/9780618346257-L.jpg", "swap_available": False},
    {"title": "The Lion, the Witch and the Wardrobe", "author": "C.S. Lewis", "category": "Fantasy", "isbn": "9780064404990", "condition": "Good", "price": 95.0, "description": "Four children discover a magical world through a wardrobe and battle the White Witch.", "image_url": "https://covers.openlibrary.org/b/isbn/9780064404990-L.jpg", "swap_available": True},
    {"title": "Good Omens", "author": "Terry Pratchett & Neil Gaiman", "category": "Fantasy", "isbn": "9780060853983", "condition": "Like New", "price": 140.0, "description": "A comedic novel about an angel and a demon trying to prevent the apocalypse.", "image_url": "https://covers.openlibrary.org/b/isbn/9780060853983-L.jpg", "swap_available": True},
    {"title": "The Hitchhiker's Guide: Restaurant at the End of the Universe", "author": "Douglas Adams", "category": "Science Fiction", "isbn": "9780345391810", "condition": "Good", "price": 110.0, "description": "The second book in the Hitchhiker's Guide series — more cosmic misadventures.", "image_url": "https://covers.openlibrary.org/b/isbn/9780345391810-L.jpg", "swap_available": True},
    {"title": "Steve Jobs", "author": "Walter Isaacson", "category": "Biography", "isbn": "9781451648539", "condition": "Good", "price": 200.0, "description": "The exclusive biography of Apple co-founder Steve Jobs based on 40+ interviews.", "image_url": "https://covers.openlibrary.org/b/isbn/9781451648539-L.jpg", "swap_available": False},
    {"title": "Elon Musk", "author": "Walter Isaacson", "category": "Biography", "isbn": "9781982181284", "condition": "Like New", "price": 250.0, "description": "The definitive biography of the world's most controversial entrepreneur.", "image_url": "https://covers.openlibrary.org/b/isbn/9781982181284-L.jpg", "swap_available": False},
    {"title": "Long Walk to Freedom", "author": "Nelson Mandela", "category": "Biography", "isbn": "9780316548182", "condition": "Good", "price": 175.0, "description": "The autobiography of Nelson Mandela — from childhood to presidency.", "image_url": "https://covers.openlibrary.org/b/isbn/9780316548182-L.jpg", "swap_available": True},
    {"title": "The Diary of a CEO", "author": "Steven Bartlett", "category": "Business", "isbn": "9781785044496", "condition": "Like New", "price": 210.0, "description": "33 laws of business and life from the youngest Dragon on Dragon's Den.", "image_url": "https://covers.openlibrary.org/b/isbn/9781785044496-L.jpg", "swap_available": False},
    {"title": "Never Split the Difference", "author": "Chris Voss", "category": "Business", "isbn": "9780062407801", "condition": "Good", "price": 185.0, "description": "Negotiating as if your life depended on it — by a former FBI hostage negotiator.", "image_url": "https://covers.openlibrary.org/b/isbn/9780062407801-L.jpg", "swap_available": False},
    {"title": "The Psychology of Money", "author": "Morgan Housel", "category": "Finance", "isbn": "9780857197689", "condition": "Like New", "price": 195.0, "description": "Timeless lessons on wealth, greed, and happiness.", "image_url": "https://covers.openlibrary.org/b/isbn/9780857197689-L.jpg", "swap_available": False},
    {"title": "Factfulness", "author": "Hans Rosling", "category": "Non-Fiction", "isbn": "9781250107817", "condition": "Good", "price": 170.0, "description": "Ten reasons we're wrong about the world — and why things are better than you think.", "image_url": "https://covers.openlibrary.org/b/isbn/9781250107817-L.jpg", "swap_available": True},
    {"title": "Quiet: The Power of Introverts", "author": "Susan Cain", "category": "Psychology", "isbn": "9780307352149", "condition": "Good", "price": 155.0, "description": "How introverts can harness their strengths in a world that can't stop talking.", "image_url": "https://covers.openlibrary.org/b/isbn/9780307352149-L.jpg", "swap_available": True},
]

db = SessionLocal()
try:
    admin = db.query(User).filter(User.username == "admin").first()
    if not admin:
        print("[ERROR] Admin user not found. Start the server once first.")
        sys.exit(1)

    existing_isbns = {b.isbn for b in db.query(Book.isbn).all()}

    added = 0
    for b in BOOKS:
        if b["isbn"] in existing_isbns:
            print(f"  [SKIP] {b['title']}")
            continue
        db.add(Book(**b, seller_id=admin.id, is_available=True))
        added += 1
        print(f"  [+] {b['title']}")

    db.commit()
    total = db.query(Book).count()
    print(f"\n[DONE] {added} new books added! Total books in DB: {total}")
finally:
    db.close()
